name: Continue On Error
on: push
jobs:
  failure:
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1 #終了ステータスがゼロでないのでエラー発生
        continue-on-error: true #発生したエラーを握りつぶす
      - run: echo "Success" #前段でエラーが発生しても正常終了