name: Secret Scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "$(pwd):$(pwd)" \
          secretlint/secretlint secretlint --maskSecrets '**/*'