name: Test actions
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: date > foo.md #プッシュ対象のダミーファイル作成
      - name: Exercise
        id: exercise #後続のフェーズから参照できるようステップIDを設定
        uses: ./ #ローカルファイルからプルリクエスト作成アクションを実行
        with:
          message: Test
      - name: Verify #実行結果の検証
        run: |
          set -x #BASHのトレーシングオプション有効化
          test "$(gh pr view "${BRANCH}" --json title --jq .title)" = "Test" #プルリクのタイトルがTestであるか
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}
      - name: Teardown # テストの後始末
        if: ${{ always() }}
        run: |
          gh pr close "${BRANCH}" || true
          git push origin "${BRANCH}" --delete || true
        env:
          BRANCH: ${{ steps.exercise.outputs.branch }}